from pydantic import BaseModel, EmailStr, ConfigDict, Field
from typing import List, Optional
from datetime import datetime

# ==========================================
# CONTENT SCHEMAS
# ==========================================
class ContentBase(BaseModel):
    order_id: str
    text_prompt: Optional[str] = None
    post_text_raw: Optional[str] = None
    post_text_formatted: Optional[str] = None
    text_status: Optional[str] = "pending"
    image_prompt: Optional[str] = None
    image_status: Optional[str] = "pending"
    batch_job_id: Optional[str] = None
    batch_job_status: Optional[str] = "pending"
    batch_job_comp_at: Optional[datetime] = None
    drive_image_url: Optional[str] = None
    raw_image_path: Optional[str] = None
    upscale_required: bool = False
    upscale_status: Optional[str] = "pending"
    f4k_image_path: Optional[str] = None 
    post_to_socials: bool = False
    save_to_drive: bool = True
    gdrive_status: Optional[str] = "pending"
    status: Optional[str] = "active"

class ContentCreate(ContentBase):
    pass

class ContentResponse(ContentBase):
    content_id: str
    
    
    model_config = ConfigDict(from_attributes=True)

# For the PATCH request, all fields are optional
class ContentUpdate(BaseModel):
    post_text: Optional[str] = None
    image_prompt: Optional[str] = None
    text_status: Optional[str] = None

class PendingImageResponse(BaseModel):
    content_id: str
    order_id: str
    batch_job_id: Optional[str] = None
    image_status: Optional[str] = None
    raw_image_path: Optional[str] = None
    
    model_config = ConfigDict(from_attributes=True)

# ==========================================
# ORDER SCHEMAS
# ==========================================
class OrderBase(BaseModel):
    client_name: str
    ordered_posts: int
    package: str
    is_monthly: bool = False
    
    # Optional here because Pydantic will compute them dynamically if missing 
    package_code: Optional[str] = None
    unit_post_price: Optional[float] = None
    total_order_price: Optional[float] = None
    
    brand_guidelines: Optional[str] = None
    client_requirements: Optional[str] = None
    product_or_service_name: Optional[str] = None
    product_or_service_features: Optional[str] = None
    business_objectives: Optional[str] = None
    business_offers: Optional[str] = None
    target_country: Optional[str] = None
    target_audience: Optional[str] = None
    target_religious_groups: Optional[str] = None
    status: Optional[str] = "active"
    
    pay_medium: Optional[str] = None
    bkash_number: Optional[str] = None
    bkash_trx_id: Optional[str] = None
    nogod_number: Optional[str] = None
    nogod_trx_id: Optional[str] = None
    bank_acc_name: Optional[str] = None
    bank_acc_number: Optional[str] = None
    bank_trx_id: Optional[str] = None

class OrderCreate(OrderBase):
    client_id: str

class OrderResponse(OrderBase):
    order_id: str
    client_id: str
    order_date: datetime
    # Omitting the full content list here to prevent circular loops, 
    # but you can create an 'OrderWithContent' schema if needed.
    
    model_config = ConfigDict(from_attributes=True)

# ==========================================
# CLIENT SCHEMAS
# ==========================================
class ClientBase(BaseModel):
    client_type: Optional[str] = None
    client_status: Optional[str] = "active"
    client_name: str
    client_email: EmailStr
    client_phone: Optional[str] = None
    company_name: Optional[str] = None
    company_address: Optional[str] = None
    company_website: Optional[str] = None
    company_logo: Optional[str] = None

class ClientCreate(ClientBase):
    pass

class ClientResponse(ClientBase):
    client_id: str
    created_at: datetime
    # orders: List[OrderResponse] = [] # Includes related orders in response
    
    model_config = ConfigDict(from_attributes=True)

# ==========================================
# HARDWARE / PROCESSING SCHEMAS
# ==========================================
class ImageTask(BaseModel):
    image_url: str = Field(
        ..., 
        description="The temporary URL of the raw image generated by Gemini API."
    )
    client_id: str = Field(
        ..., 
        description="The unique identifier for the client (used for saving the file locally)."
    )
    image_id: str = Field(
        default="unknown", 
        description="Optional ID from n8n to track the specific image generation task."
    )
    upscale: bool = Field(
        default=True, 
        description="Set to true to route the image to the local RTX 3060 for 4K upscaling."
    )

# ==========================================
# ECOM CONTENT STYLE SCHEMAS
# ==========================================
class EcomContentStyleBase(BaseModel):
    style_name: str

class EcomContentStyleCreate(EcomContentStyleBase):
    pass

class EcomContentStyleResponse(EcomContentStyleBase):
    style_id: str
    style_alias: str

    model_config = ConfigDict(from_attributes=True)

class EcomContentStyleUpdate(BaseModel):
    style_name: Optional[str] = None

# ==========================================
# ECOM PRODUCT DATA SCHEMAS
# ==========================================
class EcomProductBase(BaseModel):
    product_name: str
    sku: Optional[str] = None
    color: Optional[str] = None
    client_id: str
    product_category: Optional[str] = None
    product_subcategory: Optional[str] = None
    product_url: Optional[str] = None
    platform: Optional[str] = None
    caption: Optional[str] = None
    styles: Optional[str] = None
    images_done: Optional[str] = "0/0"
    status: Optional[str] = "pending"

class EcomProductCreate(EcomProductBase):
    pass

class EcomProductResponse(EcomProductBase):
    product_id: str
    product_alias: str
    img_file_name: str
    img_file_path: str
    logo_path: str

    model_config = ConfigDict(from_attributes=True)

class EcomProductUpdate(BaseModel):
    product_name: Optional[str] = None
    sku: Optional[str] = None
    color: Optional[str] = None
    product_category: Optional[str] = None
    product_subcategory: Optional[str] = None
    product_url: Optional[str] = None
    platform: Optional[str] = None
    caption: Optional[str] = None
    styles: Optional[str] = None
    images_done: Optional[str] = None
    status: Optional[str] = None